# Generated by Django 4.0.6 on 2022-07-29 10:42

from multiprocessing.dummy import Manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    Manager = False
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.CharField(default='', max_length=100)),
                ('branchDescription', models.CharField(default='', max_length=255)),
                ('branchImg', models.CharField(default='', max_length=255)),
                ('branchRoute', models.CharField(default='', max_length=100)),
                ('branchIsActive', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tokenization',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('token', models.CharField(default='', max_length=255)),
                ('lastRoute', models.CharField(default='', max_length=100)),
                ('isDestroyed', models.CharField(default='', max_length=1)),
                ('isvalid', models.CharField(default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('userType', models.CharField(default='', max_length=1)),
                ('isLock', models.CharField(default='', max_length=1)),
                ('imgURL', models.CharField(default='', max_length=255)),
                ('occupationStatus', models.CharField(default='', max_length=100)),
                ('occupationDetails', models.CharField(default='', max_length=255)),
                ('occupationPositionWork', models.CharField(
                    default='', max_length=150)),
                ('nameofschool', models.CharField(default='', max_length=100)),
                ('degree', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
